elves = [
"DsPhSBQQQhqmBDhPDsFwjwsLjlRjlttvjvvtRb",
"rNJMNNbrHrtjHLHjvwtg",
"fNbNzZdrZnMnMPnQShFPDmnqFm",
"QWVCFfQffgQCVZzVVpHsHJBqtpspJFRHqq",
"mwDbmnnGNlNcwNDDNRbnNDlJTpBJBtJGtPTLsBGqTqqsqp",
"MlSdnScRnnmmDjSdNSdCzvggWzrgzjvfvrgVzW",
"gsMljbrjlZlWcWMJrWwTwbmwQbmmLDQQLhwL",
"CdgpzdgpgnfThHfFRwhfRf",
"SptgpSpnCNpVSGNPvPGSddcMWjMrjqBsJcWqMcBWcVlZ",
"JcJLQQFWhQJPJpWcwjHvMQvnnlMvzBHd",
"tCtGZrmVRmVGTVTtCfRTCHHNNvdNzmdMvMlNzvwdvw",
"CTGGRftfSGtGTGDLbFchSgSWWWcM",
"QcMFQrvrQbvtczbVbjbMzZzRpqmDDmqqnNzCDCDC",
"SHHfPJssGLPSdHThLhHdRmqNmNssnNmNCNnpjmsn",
"LhLJfTdLJwfgPTdfGccrtjcMrccwvcrrFr",
"jFLLLqDGjbtqLCChpMMhMBvpwMTmffpZ",
"ZnJHRncHHgnrsrZffTdMdMBfmMvfvR",
"NWWPnZrVHrZPCDDQtzDCPLCq",
"jpFjvBZhDFHZdwcmslcslBLLNl",
"dVtTVVCzzfrrMPNLLcnVcPLRns",
"CrzWzTqdWtGCzJtbJCrMjjDFHZQjZSpvFGFgHhHp",
"JjJqMctnhtDZDQtf",
"TrFFlrrCCHPwHwlPHFPzDhsffQQDsVfWwVJQJB",
"HHHGdFlHldTpCCFFlLHdCRJccMnqvqMgnNjjMjjvLMLcSv",
"cMfFcMFcrqgJLFZdrTDdthPGsGmtGs",
"WwjNwnjjBQzVVQHwRDnmtPGhPPsPnnTGld",
"bWHBjWVzpbRzbmScqgZMFcqf",
"RJjPTBJhTNNjfPhRBdqtlgdbGldwtCPgdb",
"ZmrHHmzpvSvvpzvmvDVCGlWVwCWtGtWCddggqf",
"QQpzFrHHQnzHvfTcNshcLRNFJhcR",
"QrPQDrppBQmCmFQm",
"TzqzsLfmsfSTfqzVLftNdJJNJGCwwGdgCwSGNC",
"TVHTfzWsfftsZstnbvrbWbrbppPbrmmP",
"BQrfqrLtJnttqqtQBJDDtBnDzRgldhVVpJlgzpzhpzsgslhV",
"TTNcPZCvZjmPFZjvPHLlWdNLghVhzzlllpVd",
"jcFPbTcZTFcmcjMjjFjbLwbnDBtfqbtBwfwSBnrbGw",
"SZJNJtrNzjjNCzlBBmqmQDBBmDBBjB",
"PGPbGwhLsnvwnVbGPVMZsDsTBBgcZgBBDBfDBf",
"pnnhhvphGVpvRPnJlSFRNNJHZHSdSR",
"hbmDDmwnnVGbhmjNrrWwLNLsWBrw",
"dMrgvcQqdjlBLlfW",
"HzzPSrcHqFHQgzpPcMpQqrtmbbbRhHHVGnZDnVHhVbVZ",
"RwtvdPRvSlTQmHHBQBRL",
"FjVSjrsFVnFQnTHmnT",
"VCVVMrWWjVGgbcNVGCCVdlvfdqfvwbSzwqfwZzwv",
"fmPDwJPDFRmRgPdwwwDNwgwPzhSQzVSzVTQdzHZzHhzQMQzQ",
"sWtGCWtpcqqpNnQjjzhVTTVQczhj",
"tWBGntsCNlqrWswDRfFrbFrPDbPf",
"dmzmjcbQjjQztFNqsqBcMJqNPF",
"nlTWnClWwQDTVnTrsMsCRBPZRJRJqRJq",
"wTrhwpVVvgvlDpTvVWVDdLfzgbLtbzSQLSzzjzLz",
"RWZdHvRdBRGbbvCjJnbn",
"pqqpSwzpSSbCwPwjlwjl",
"gDzzqSVzqrThpDBtRtCZdQRQLrQQ",
"GRqTGqtmTVdGHHVVNNlhPlMqbNqNDbqW",
"LzQSdFnfznfwBcLcnFppBBDDMPMPhDbhlwbWPlbWMjrD",
"QznFnLZFvVvHRgsddG",
"BBHBfBHFdSltmWJvqtNtHq",
"TQDrrVMzVDnWnNZDJc",
"gWzprTCrCMQzGGjjhwFwdffjfl",
"LLLSSSzBBlBLsszncCBZSPSMMMpdWTdrmmnfVGVmMfmrmm",
"DghttvwhHRvjJthNJwhVtDHGpddMWdMmrMmfGdppjWTfpq",
"gbJRthQDDRvwtDhQhDFPcVcbPczLzPBScBBF",
"sZsZpTtLCsbspZtTwrCwrwtDmNNdJmmqSJfqmfNGNmHqGdqb",
"nQvjTcjQglFVlllMFMVFqWfNqnNHHHdfSfHqfSJq",
"hFvvgFcFVzphpTrrwZDp",
"qJqfhsBpfSpchpqcrqwCDvvCDQndmpwDtnRQ",
"jWHPZWWjZsCmCWRDmQ",
"PPzMGHlzMNsPLPlZsllgsNrhNVBqhFVBbBSqFFBFrV",
"RnRsFFdSzmgwvQsqwc",
"lbgHGMBHlWWWlfWGGBtGwqDpDwmcpMrrqrQDZrMZ",
"GGJLBVJbVGjGtHVfJtWGHBLLPdzdCghnRnRnSShgNnhnddhj",
"VgzLFjjwhhSwFhVZgRhRgHHCCvdZdrqqCTvBCrqvvr",
"ncnNbGMcPpvHFrssdBHM",
"cnctcNNbQGWFJctftgVmzShzzwwVwgmwfR",
"pFWmSSFGQlvTbwWTwH",
"jdBgNhRgMftNBhPbhHnZHlTTZcwZ",
"lfBNRjCtCfMjsBfCjgfNBRMppGpJqsJQGrrmmJDpGmDDFG",
"GznngnhzccVdgjbbVjVjVbVLwwQJmQMrLTZhJmZLQTJWmm",
"pDBSslPCFPCpvCqvpPBQTlQLrdlJWrLJLmrlrr",
"psSsBptpCBdjtcjNVcGG",
"sssppsmchwspFLtvHhQJMtFb",
"rRLDqRVLNSMvFSSV",
"WDrLnzrDqzRqRzzfLgRnzrnsssZZZsZBgCwwmBppwBspZc",
"MtPbwvzzVtzfsqGGVpdSjsLd",
"DnNRCDJBnHJDHDnrDTRcnNZpZSsSLqjpdqqqSMqdddTj",
"CFRFRFHgDRnRgMtfFvvwzwvwvzWv",
"PNpFPncvvchPpNjpFhvPhPLmBwMgDRRwRgMDhBmLzBDD",
"trHSrdTtslWrSWmfzgmMnfBzmn",
"JsrQsJHHlsVqTjjpbbNnQNNpGG",
"sVQCdsmGlnlCmnGmQQhGCJJNvNjpgqhqhvPgpgPqjpcpcW",
"DMSfSbHLHbSDBBzLNvccWRcddvPjNj",
"FSwHfTFdFsmJlnTTmV",
"FctwtTTCScvShFqtwScrcTSCJQGNndGHWJNQHWHZdgJrJgGN",
"jspLlfPlpfsDjBspfllWgdWHQggZHngHNGdsWJ",
"lRMpBlPmSFRTcvZv",
"TVZpRRVvFRVpTZRfFhFvvzGVwrwwwdDBMwQrgcDtMtDDwZrL",
"jsNsWqWjNQCNWbjPMcBLPgBtrdMwdrdL",
"SJSsmqlSNljbmlNjsbQVffzGRvzmmVhQpVGz",
"BFFMvcwMwwpFFfpbDMqPVgLVgmLDPR",
"JtSsSzJssQJJWjRZzgLnDgqLPZgzbg",
"dsdtWQWdRGjTRNQNQvGfHCCFpvfGwlCfCp",
"zzWGqWnqnwWCvCrHffHRpBpBBRSJzRFFDhSQFR",
"VPVsZMNTLsMvPsmBJhllFpFBTJFQpl",
"sZtsNsZtdZgjbwggjnbvqr",
"QpTvrphmDvvddfcJJHTTncMlMG",
"bRZZPRwjgzzlSSjGlnlSJS",
"BZzBzssWgwzzwNBsgsPBgszmQptqrrGdvdWmqdhhFQDpQF",
"FfMtzSqlDlzfMhPFhPtffNRsCgSgCCGspRpRGSsgsg",
"WTcWLTTVnWmrVdLrcHmNGNCZwCCggpgDRwpCnR",
"JcdWJHTJWdJdjJccrLvlFltFQQvPFDMjqqlP",
"NfjFNNZPDQVJVWpCbQpJ",
"lcmdzlmzBtRSTlTTcncsVSbhpLWpWgsWghgsVS",
"mBTRRmGccRtBwDbrGPbrMMrF",
"VVQqlsGrVsMWBNFNMQHF",
"TfzZfDgjgnLGjjztTncCFwwNmdvNcwwNBvHNFwvd",
"jzjDgZzjntGJZzCnhrrSlPVsJslpslPq",
"dVhpjGPdjHhqHgtHJJ",
"sFzrzllQswDwFbcmBlgvZTCgvqTCfgHQJtqT",
"nDbBsFzzrrtFrlwzPdSVMWMVVMSnGNLd",
"wqJCjqChmwMLmMmprNgG",
"DNTtdsdWcHdNspGQggnrgLnQpc",
"SZvFftdddDsDTtttTDJNCCwJJZzbbCjwwVPj",
"VstwZCwslBZQDBjfDDBDfS",
"rvHnmMRrTzmMrmhRppbhDfpjfbjbctjD",
"rPFLRLmFvvLvHvTCtqsVVwldGZGPGV",
"SNZDJGfvwgMgfgmLmLcmBqgWgQWr",
"hPnPTnVGsPRqLWpTmQqQ",
"tsbnFhhjhSdGJNCjSf",
"QSbGgBjfTCMWFNPFFtDghPrP",
"JqHqJVzZzwJJHLlqQptDhPrctpPDtnLF",
"zZmwJwdwdvHddVJvZqdzHlfGBbsCmMTsWCBCjsGGBbMQ",
"gVmLtpWrFTFBLtpcFNbvhNNnTnvnQRlQQv",
"GHjjqsMqwZZJdqGfZjfZGjQDDhvQNzznzRzRwDNbvgzv",
"sZGPgssMqHZpPptmCcpCrP",
"CZCNNLmwzwCGMZQMQsFNWplvpsJBWpFHBp",
"SPbSbDRRbnDqggnbVbVrbRWHJFTlBBcTvWvsPvFpHTcl",
"tVgSvqVbnqDdgQzMQMGMmzthCw",
"mpbPQlblbwSlfSPGBpBGPpBFgMMtLFSHMLVVDVdtHLNctF",
"WnhZsrJhTnWrgZdZgHNLcLtt",
"hjCsCWRhjzhTjnWnQBbmPQQPLBGfqjwQ",
"BFrzdtmRmpFtFwwmjjzNQllPshqHvjNh",
"fWCLLCMJnCDbgfMJhPsPHvqvqVsssQ",
"WbLnCZnvprpmZrGd",
"gjMzTGBjWFBCCSSrBC",
"bddJJndbdJfwPPthrrSSSsFSSg",
"NJHbZbbvvWGgjWgT",
"dpfphMggHdQcwftMMgdtzWGfGWnDBnmvnVJVvfmn",
"CqPFTZPSNCTsZZZRLzGmcGVzDLGvLWBWJm",
"TCrTNSScPlplpHrQrQ",
"lqrCvhWFvMGWgfHPgLfjfdgG",
"zjmbjSnzRzVVRmzBRtwjVQnNLfdPgfLdfTtNLPHTNNpppf",
"mbSZRzQRBnnzbQJbmjmSbmVhlslZMrclWFrrqWCWsFhchF",
"mpfNshshflNthWfJCBBdmnQbQBZQdn",
"VFVRccgGTqTrHTbWBFjJBCFFJCCQ",
"PvTDHqHqPPGVqqhwfNlWlDhMltlh",
"HmLLgWVjJwhwWLgjjhmVHLLLlSzBlBlSvBvBFGvtdStJSSvq",
"TRRrPMsfQTbRRCZRnTMRZZTCcvSccqBqBBlzdFvBqFsGBcts",
"bRNPbRCZMCrQNfPLdhVpLDVgDhNHWV",
"sPJFDsSsVLgHjLHPbj",
"vCnRQhhRQdVQZlZdbHNMlqNNjgjbpbBL",
"ChhCCCWTWnnmvmGtztStzScwrcVcFW",
"NRBTNDBglSSgDwCClQQSFFHdLLsFbPFFLt",
"McpmWccMWHZPcLstbt",
"MWnWphVMvvzJzpWJWmVphjrDDBBTRwRDDDRRCnPDnqgg",
"hsnnhhLljLPTmZwvdZdZjmmz",
"RQNNDpNMSZwvsmqstN",
"QFMFRDVDsHSpRpHSMRHfGGGTLhCChBGhBhBFBJ",
"TTbltCvClzvzCZtwtwLTtQQQgjNgmjgQRRRQSjQLjR",
"HPpnZHcJsdnnfsdVHHSSqghhmqBSSqSmBfNj",
"VMJJdnMPrMGVrzvCZwZWCzCt",
"CcQnBBCfBvRzDlsS",
"PdbPPCbhGGpDSDlDDhvDJl",
"HmHWPWdbHnCwCHCr",
"JHlmJcMWHQcPmlmJMmMZPfwTTRDfgdDBfRtgQgdfBw",
"zVvFrqGjzWGVrqvjvNFpspvVBgNNddtTgghhRTwgdDwwwBfT",
"bVFrrvsvjWGVsCsqpSHZmMPJlJnCcLcPZZ",
"QrrQZFZnRtnFRTrnlFTtRZwpGGwzGszhjzbsGzzhmjjhhmhf",
"SgvpDSJSgPBSDPDNgpggmsMhMmffsMmzfJmzHHMj",
"WNVcCPgSSDCddSdWCpNBclCQQFRQQlnTLFLRZQnLtt",
"tgvqWqzvntdlzNzzHrbPrMhHMhhrVrjPmC",
"FGTGGRGTffcJRpQcJJwmjhPLhjnCQPrLPVQrMr",
"SppRSDRwFnJJwwswTDdtzBzqWWzZDldNgtvl",
"sjzPjLphMSrlppSp",
"fbGqgwTqgVTFFcgGTTGcQvfHQZRlSrSlSmMNMBRNNNrZmm",
"MVcFGTFtqjsJLjjtCd",
"jVJqTRHjjtDjZnVJVVjnNdwfCFPZmPgCCgCZGCFFrrFg",
"LSLBMBWsbBBCgfdrFd",
"ShbbzdzQRNNNVhDN",
"JwbSRqmSwRwcpmbSSVfhNBTVGGRnNNzRNh",
"ZPfQPjZZrffQZszhzTnVGBvntsNz",
"rLjggjQgQgFdPQjLFQZgwLMbWccLSwWHqHfSqpwc",
"cBhzNpztzHNrpHSHQrhZjZqdJRRgPqjhjqqP",
"bQwsMTswwVjdZMVRJM",
"vGWCTDCTQvvtlvQQ",
"mHVmTTsmzRmRHffmmfMGBzSPMhSWWdDWDSGB",
"VNcnNbtqqJbcbvgvWhShDBDPhjgPhSjB",
"FrrbCnqJcbCJcFFbnqJlppCTfQmfmZQTLVswRLZp",
"rWWppSStfRBLfHPdHHDzlldZ",
"QrTnQmmVCqvrvJvzJZPHvzHsDs",
"qgMMmrTTCcnQQmCNQNQmgTpwRWRtwtpcBWwjSRSSpttW",
"SzWQwwqVbQzwGSfVwffVwbqhFGFFMgGLGMlNMcnNgcvlMg",
"ddZHHsrCdBssDsHmChFLNNnMvmNnnnFncL",
"rpJJdHZJdZHQSRJbSfVhww",
"jLtFhNwNNvHnjFVvQLQLHhfbGDMPfffpllpttZMPPZZb",
"VmrqszVmgCWWggbPGclPlZbcZCbf",
"JdrTmVTVsqsRJHvQnnhwhBLH",
"vpdBvsvdVvSPhvQFCgrRmhjqqRgWcWWgmf",
"tJDGbZHbjRHNrrBj",
"DnMnzGJJwtzVSzzBzTBSTF",
"hZMDbQhMhlMDJrDrPMJRRqGJSvFvSwFSVdvGvwSFqq",
"HjjzcRTnpGVSGGFWHH",
"pssmjctLzpsRRnhlQbPfPrgDbZls",
"FJMhPhnTMGmBFdnmlrfqfCcwlwCwCv",
"pjHLsLbjjRHsHsjDjVsgDRjzCnfCfzqrqvwgflcvcvvgqz",
"njtpHZnLLQGhTtTWSSSh",
"NMddMTDrrjNnrnMWMrlnPwNwftBtGvptGjBHgBgpfCCSfgvf",
"mqRqLFZRVFbtgBSCbGWWHp",
"LZZRmQhVLLFzZdTQPndPNTTnQW",
"CprQrcpqhHhpppchpphdcdpLMRMGsVGGsMsLbZbtbfMRmtbG",
"DzlgTjwPTlSSSCDSlggNmMRtbsstsMfbwtVssMmt",
"TNCNSBNJJTNPJjCTBDzjlJrvvcQrrhphWBqHhHdqrnrr",
"ScbcbglMPRSmvclTlzMTdhVHhhjfdsdhrVDzfjrD",
"LJGtpQwpQBBCttJLGqtqGHhPfDdHwjjhrVrhdrdshr",
"WCpZQCGqtqQWtQWplZPcvMmgmvPccbvT",
"tGWqthqGVdzBWwdd",
"BZvZHFFHZrHZvZNRRHHZNHrMMTzRMTdTzbgDVMVssTDTwg",
"JnNmrHHNrCGBPPnGGc",
"wvFvZBmppBdSLcvshcLrgl",
"bTQqJJHJzJjDQjQtzRVJztDHslgNNVLcgSrsSsWrSslWgrgL",
"TqHHjQnbHTbbmZBBcFMpmBwn",
"ZFCqSlCPdCRTLWWTQQLLQS",
"GjggHcvsggHVTVBLnlcpBQ",
"hvGhlrtjmjrHHhjsMPFNPdtqMPqqRfCf",
"cgRwVfVzrgqqwZctTztFMFMTCdPmmF",
"bWJsSJHpTDRDTWMC",
"sHHNbshnlJhJjBsjsbnBHbZcqrZZQwqvvZcrwwvRcZnr",
"ttgVBtMbttngmHJVpzlzZlppzw",
"cPcsRPmPPQfGcccRQSSZzzvzlflzZHvJppzJzT",
"sQPSCPPWccWWWqsQqRCQFNRMmnbnjjNbgDdBjhBrdbdDbd",
"gSsZDSgdQZgWSgddwLDLLfCDBqvlhBlClqtqjhvBhB",
"RMcsVMcsbVsrPrmJcPHHVvfjjCnvvfCqhlqvqqqq",
"NFMRRpHPgzszGppG",
"WmmZZNJCgCBZCzPvmBCmjWjjqFtFqjFjbVwqwjtt",
"ppDMpdMfSfSSNtlwqbqwwq",
"dTGDhdnfLMLhfDDpQvZNZgmrmrQJgrLQ",
"jrqRqfNNhrVvcTVdpTscpd",
"tGWBlLggWGddTspZZd",
"JJzWtQgQsDbBgDWsgbFrPrRJNMJMPqMNfHjH",
"GdvVbbWsWdvWGDvWZcbFBTBZCzCjwzrhPBJjzF",
"nQPfSHnglfpnMSngnMgJTprJCCwwrwCwpTpCFj",
"SQQHSttRqggmlVsNcvWdRvbWPN",
"WLNLCWLsSJgHFrSHrM",
"gDbzRTcmbzPPgPPdtBctfHfrMMQfGFJrhQnMfGJR",
"dmmzzqZdDqqTLLwjgZgNljws",
"TCqsDHssmDsDGVGlVcMccGDV",
"FLntWWnnFzFgzzbtbznLBtlfjGZmcfFGVNFGlVZcMNlN",
"PpbLLmpgbRzqpCHwChQqwh",
"lVBPVgflgBVVrVTTwgwBPmgflDQjnnGvqjGDDFjGlGnvqHHJ",
"ScCLzdCZdbLSbFdFqvDDdGMQGQ",
"bchNCLRWSbzCbNRzbWRmsrhQwVVwBhmQpPwpgV",
"GmfHCCPqWqHLWLCfRJpbrrbQphwZbZ",
"STVDQzNnzMzNdstMDzzNtZwFhrlwVJJrJlFFJRFwFR",
"DzSvzstnszMnjQcqggjPqQBcqq",
"BzNwLTqwTjrBrljWpBlrQpBpsCGGCtpssCMttDtHsttMDCHp",
"mnrJVmRhhvJVcHtsGHMCnZCPZM",
"bvSmVbRhbgmmSJflzNLrzqzfWfqBWr",
"qsZLqqFNhfrGnJFv",
"DVjVmWlcjVjdDTDlbbTDTzmrCnMmJGnHnmCHfJGfvnfM",
"lVRdDglTlTgVlVjbWWVzVjvNZqSBsLZNtqRsLBqLqQtL",
"ffRRfLVHZHfJHVJcMrMZZwwTzGBBzBTBjGTwrwdSCj",
"qmWbWQbqnbvWhbQPGnGNnpvwSzltpBldtSdzllptCSjTTt",
"vWsbnbWnNvQQQQvsRRLfJRRVGfDcfV",
"PpqrvswPvvvPsNqmDLDttCCcHHZVrCtW",
"hgSddBhghQMdbhbwhgSdQgCCctZcDtLntLttCVLtSLCc",
"dGzdQMFzQMdgGGlGJMzBgBwRqNNfmmTsvfRfJTpwjmpP",
"pcphpdrWDmTgHWMtRWqHRVVH",
"SbGcGGQnvNQGvsjBtVHBLjvqVPVB",
"lzbQCzbZllSzQslpCJpJJDggcggfDT",
"ffrTlhrVrfCsDVTsWzGBBZcBRBqRBWtGtZcq",
"QNFmFHrHNSSmSLJdJrNGZLbGjbcBjBGjqcbgjc",
"ddQvPnHddnQJHSHSFPdnFfDDTfDMMCrwMlPTwDCsrC",
"NBnrNHQHBscvhfBM",
"bbGtgWWWqZFmnZGZbmVCdMzvvShfzfGcdcfMSS",
"WqbjnmbnjWgmFFgtWVbWZwNTNLjNprNwQLDwrTrHQr",
"lwwlcjlzQRBcBccbdLCVnNVWJJzfLndd",
"pZDMtZpSDMZpMZMsPtHVNJVfRCRddVndnJLSJd",
"mDTZvTqtDDHttRPcqhQlwgGlghbqBh",
"DTspTqssqTbdmCMwVmnmlfCD",
"PLPWjjrSjvPzqZvjvRqjLtPwnnHCmWVcncMnnwmncHcHll",
"RFztFjjqjQFQTbdTbQ",
"hTFSVSdhMMVMFjjgbthcbzczcg",
"DvwCJVJWWJDRnfmbDmccfmmgfb",
"QrJvPGWWnpVMqdZsZpqM",
"gRLcHbgnfpgpJjlqqp",
"SFwrTHFBqlZtBPZq",
"HTzDwmSvCvCmsmmvTSwvFwcfRRNRLcQRWNssNNbRWLWL",
"PpMgDMDnsWSnjBQnrjbn",
"LFcVVGChCFdhdVFZVpVCdVbvQbRrbvBBbBjQSJZrrJrR",
"FNwGNCCFHcVTHcFdHHHTDzMzfsgzwpPWMmPflmtt",
]
prio_a = ord("a")
prio_z = ord("z")
prio_A = ord("A")
prio_Z = ord("Z")

def priority(item):
    prio_item = ord(item)
    if prio_a <= prio_item <= prio_z:
        return prio_item - prio_a + 1
    elif prio_A <= prio_item <= prio_Z:
        return prio_item - prio_A + 27

def common_items(left, right):
    return list(set(left).intersection(set(right)))

summed_up_priorities = 0

for sack in elves:
    left_pocket = sack[0:int(len(sack)/2)]
    right_pocket = sack[int(len(sack)/2):]
    for item in common_items(left_pocket, right_pocket):
        summed_up_priorities += priority(item)

print(summed_up_priorities)

badges = 0
# part 2
for i in range(0, len(elves), 3):
    elf_A = elves[i]
    elf_B = elves[i+1]
    elf_C = elves[i+2]
    common_a_b = common_items(elf_A, elf_B)
    common_b_c = common_items(elf_B, elf_C)
    common_to_all = common_items(common_a_b, common_b_c)
    badges += priority(common_to_all[0])

print(badges)